theme: jekyll-theme-cayman
title: Welcome to Ruoyu Li 's Homepage
description: feel free to bookmark this page to keep update my project progress.
author: RUOYU LI
author_email: ruoyu.li@mavs.uta.edu
permalink: pretty


[navbar]Brand reference
***
* Hierarchical
 * list of
 * menu items[/navbar]
location: built-in
